### ISSUE TITLE
No scheduled commands are ready to run.

### ISSUE THREAD

**Issue by vijaysebastian** [loduis/artisan#3]
I am trying Laravel schedule command to run some background process for sending mails and fetching emails. When I run these commands individually using artisan they all run, but when I try to run shcedule:run command to run these commands it shows "No scheduled commands are ready to run."

I've tried to look for an answer but nothing worked. So I tried to rectify the problem by running simple command and check the output. Below is my kernal.php
```
<?php

namespace App\Console;

use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;
//use App\Model\MailJob\Condition;

class Kernel extends ConsoleKernel {

    /**
     * The Artisan commands provided by your application.
     *
     * @var array
     */
    protected $commands = [
        \App\Console\Commands\Inspire::class,
    ];

    /**
     * Define the application's command schedule.
     *
     * @param \Illuminate\Console\Scheduling\Schedule $schedule
     *
     * @return void
     */
    protected function schedule(Schedule $schedule) {
        $schedule->command('inspire')->everyMinute();
        dd($schedule);
    }

   
}

```

when I run schedule:run it shows this output.

> BhanuSlthiasMBP:Faveo-Helpdesk-Pro-bhanu-fork vijaysebastian$ php artisan schedule:run
> Illuminate\Console\Scheduling\Schedule {#54
>   #events: array:1 [
>     0 => Illuminate\Console\Scheduling\Event {#1680
>       +command: "'/Applications/AMPPS/php-5.5/bin/php' 'artisan' inspire"
>       +expression: "* * * * * *"
>       +timezone: null
>       +user: null
>       +environments: []
>       +evenInMaintenanceMode: false
>       +withoutOverlapping: false
>       +runInBackground: false
>       #filters: []
>       #rejects: []
>       +output: "/dev/null"
>       #shouldAppendOutput: false
>       #beforeCallbacks: []
>       #afterCallbacks: []
>       +description: null
>     }
>   ]
> }

But when I remove dd() in schedule() function the output is

> BhanuSlthiasMBP:Faveo-Helpdesk-Pro-bhanu-fork vijaysebastian$ php artisan schedule:run
> No scheduled commands are ready to run.

Please help me, I am using laravel 5.2

**Comment by loduis** [comment]
Hi,

I fixed this, please review.

**Comment by vijaysebastian** [comment]
May I know how did you fixed ?

**Comment by loduis** [comment]
It was a minor problem that was missing a slack, look at the commit in: https://github.com/loduis/artisan/commit/805b5cc49dc42aca5fddffd91fc3ae10bf388bee
